### ISSUE TITLE
Text block language reset when typing

### ISSUE THREAD

**Issue by x6251962** [ONLYOFFICE/DesktopEditors#1806]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

8.3.0-97

### Expected Behavior

When I type text in an Onlyoffice Document, the language of the text block remains the same as it was previously I set or it matches the language of the document.
Yes, this work in previous versions of Document from Desktop Editors (E.g. 8.2.2-22).

### Actual Behavior

When I type text in an Onlyoffice Document, the language of the text block 'disappears' or is reset from my point of view. That is, this parameter becomes empty (the value is not specified, the panel will be empty). If I select the current language, the selected value will be set till I enter any first character, then it will be reset again.

### Reproduction Steps

1. Create new Document (text).
2. In bottom left corner you'll see current language of text, then globe icon and spell checking icon.
3. Type anything you want. The name of current language is empty now.

### Additional information

I met this behavior today, after upgrade OnlyOffice from 8.2.2-22 to 8.3.0-97 from repository https://download.onlyoffice.com/repo/debian squeeze/main amd64 Packages.
I was unable to type double quotes (U+00AB and U+00BB). After I double check the applications behavior I found that double quotes are not entered due to the constantly resetting language of the text.
When I found a reason, I downgrade to the previous version of the package in the repository. This helped to solve the problem.

**Comment by ElenaMaaya** [comment]
Hello @krischan941 !
Thank you for report!
This is a known bug 73192.

**Comment by parrenin** [comment]
Excellent @ElenaMaaya , thank you!
Will it be released with 9.0.0 or before?

**Comment by ElenaMaaya** [comment]
> Will it be released with 9.0.0 or before?

in the next release

**Comment by Rita-Bubnova** [comment]
DesktopEditors v9.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by parrenin** [comment]
Sorry, but I don't think this bug is not fixed in 9.0.0.
It still happens to me.

**Comment by ElenaMaaya** [comment]
> Sorry, but I don't think this bug is fixed in 9.0.0. It still happens to me.

Thanks for the feedback. I will check the problem and tell you the result.

**Comment by x6251962** [comment]
Upd: On Ubuntu 24.04, in onlyoffice-desktopeditors (9.0.0-172) from repo/debian squeeze InRelease  bug is fixed.

**Comment by parrenin** [comment]
On Ubuntu-25.04, flatpak OnlyOffice (9.0.0.172), it is not fixed.

**Comment by parrenin** [comment]
A screencast to demonstrate the problem:

https://github.com/user-attachments/assets/f931c7cb-a4d5-46b5-af50-d3e775be7f47

**Comment by parrenin** [comment]
With the pointer in the screencast it is better:

https://github.com/user-attachments/assets/e7f5ab45-8420-4c69-9628-4aab92f74a5d

**Comment by Gladox114** [comment]
On Windows with 9.0.0-172 is not fixed at all. Like in the video, its switching to German while everything was marked as english and even the document is set to be english.

Please Reopen this Issue as this is not fixed at all.

(But when using Cryptpad, its working online)

**Comment by ElenaMaaya** [comment]
> On Windows with 9.0.0-172 is not fixed at all. Like in the video, its switching to German while everything was marked as english and even the document is set to be english.
> 
> Please Reopen this Issue as this is not fixed at all.
> 
> (But when using Cryptpad, its working online)

Hello, @Gladox114! It seems this might be a different issue. Please create a new issue report and attach a video along with a detailed description of the problem. 
Thank you for your cooperation.

**Comment by ElenaMaaya** [comment]
> With the pointer in the screencast it is better:
> 
>  Capture.video.du.2025-06-20.15-40-24.webm

Hello, @parrenin ! It seems this might be a different issue. Please create a new issue report and attach a video along with a detailed description of the problem. 
Thank you for your cooperation.

**Comment by parrenin** [comment]
OK, I submitted #1956
