### ISSUE TITLE
Wrong characters displayed in Spreadsheets

### ISSUE THREAD

**Issue by kingma-sbw** [ONLYOFFICE/DesktopEditors#2076]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows x64

### Version information

Community-Version 9.0.4.50 (x64 exe)

### Expected Behavior

Without styling open a cell and type `äÄëËïÏöÖüÜ`. Expected the cell content to be displayed as : `äÄëËïÏöÖüÜ`

### Actual Behavior

The cell is displayed as: 

<img width="163" height="46" alt="Image" src="https://github.com/user-attachments/assets/bbc78280-0781-4dde-8876-cc24cc8ec447" />

### Reproduction Steps

1. Open cell, by clicking in it
2. Type  or paste the text
3. Observe the content

### Additional information

Changing the font from the default `Calibri` to another does show the proper content. It seems to be a problem with certain fonts however it does not occur in Documents.

**Comment by kingma-sbw** [comment]
Just out of curiousity, Why is the font in Spreadsheets different? Why not default to the other applications font `Arial`? Yes I can customize it of course, but setting a default to the only font that causes a problem seems like a bug to me.

**Comment by seriousfreezing** [comment]
Hmm, I have a similar problem, but even after changing the font, the problem remains the same.

**Comment by VladimirProkofiev52** [comment]
Hello! @kingma-sbw I’ve reviewed your issue but wasn’t able to reproduce it on my side.

Could you please provide the following details:
- Which version of Windows are you using?
- What regional settings are configured in your system?
- What regional settings are selected in the spreadsheet editor?
- Have you installed any additional fonts, or are you using the default ones?

**Comment by AdminJoT** [comment]
I have the same problem even on a fresh installed Windows with OnlyOffice 9.0.4.50
Which version of Windows are you using? => Win 11 Pro 24H2 (26100.6584)
What regional settings are configured in your system? => German (Swiss)
What regional settings are selected in the spreadsheet editor? => German (Swiss)
Have you installed any additional fonts, or are you using the default ones? => no, default fonts

It does only happen in existing documents and not if i create a new document.
The same document in Office365 works without problems.
Sometimes in the same document in some cells it is correct and in some others it shows the wrong characters.

<img width="1023" height="1489" alt="Image" src="https://github.com/user-attachments/assets/ecc39b70-95d9-472b-aba0-7245182426db" />

**Comment by D33M0N** [comment]
I have the same problem with "Community-Version 9.0.4.50 (deb)" with Calibri font.
Using same workaround in Spreadsheets now, turning sheet font to something else. Right now Arial.

**Comment by kingma-sbw** [comment]
> Hello! [@kingma-sbw](https://github.com/kingma-sbw) I’ve reviewed your issue but wasn’t able to reproduce it on my side.
> 
> Could you please provide the following details:
> 
> * Which version of Windows are you using?
> * What regional settings are configured in your system?
> * What regional settings are selected in the spreadsheet editor?
> * Have you installed any additional fonts, or are you using the default ones?

Unfortunately I was not able to reproduce this error . As I run an automatic update script it might have been a fixed but. 
Current version 9.1.0.167  does not have this problem for me.

**Comment by VladimirProkofiev52** [comment]
Hello! @seriousfreezing @D33M0N @AdminJoT 
Could you please check if the issue still persists in the new editor version 9.1?

**Comment by D33M0N** [comment]
> Hello! [@seriousfreezing](https://github.com/seriousfreezing) [@D33M0N](https://github.com/D33M0N) [@AdminJoT](https://github.com/AdminJoT) Could you please check if the issue still persists in the new editor version 9.1?

For me in Manjaro/Arch repackaged "Community version 9.1.0.173 (deb)" it is fixed.

**Comment by AdminJoT** [comment]
For me its also fixed with "Community-Version 9.1.0.167 (x64 exe)"
Thank you :-)

**Comment by seriousfreezing** [comment]
Unfortunately, it wasn't fixed for me. I'm using the pt-br language, and letters like “ó, é” become “û, è.”

**Comment by jrzabott** [comment]
I'm also affected, btw...

<img width="1122" height="763" alt="Image" src="https://github.com/user-attachments/assets/a84bef0a-4f38-48ce-87c0-90e3d9c31ee5" />

<img width="691" height="704" alt="Image" src="https://github.com/user-attachments/assets/3827ca50-6721-432d-8877-4ec3096fa8df" />

**Comment by theking2** [comment]
It si still happening. Do you want me to open a new issue?

## Linux, Fedora 43 OO  9.3.1.8

<img width="888" height="547" alt="Image" src="https://github.com/user-attachments/assets/7b315da3-c056-4c9a-8b9a-0c072d096ffa" />


## Windows 11, OO 9.3.1.8

<img width="730" height="461" alt="Image" src="https://github.com/user-attachments/assets/8e861f13-4d00-43eb-9739-e5a865c00c47" />

## Document

[Spesen2026_Experten_Vorlage.xlsx](https://github.com/user-attachments/files/26859564/Spesen2026_Experten_Vorlage.xlsx)


## AS PDF printed on Windows
[Spesen2026_Experten_Vorlage.pdf](https://github.com/user-attachments/files/26859733/Spesen2026_Experten_Vorlage.pdf)
