### ISSUE TITLE
Not loading systems fonts on v5.4.2

### ISSUE THREAD

**Issue by uncertainquark** [ONLYOFFICE/DesktopEditors#294]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Not loading fonts installed on the system on v5.4.2

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Try to select a non-default font in a file or open a file with such a font.

**What is the expected behavior?**
Should detect and show fonts installed on the system and allow to use it.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v5.4.2.
It works in 5.4.1

**Comment by XDmitryK** [comment]
What OS are you using and how install Onlyoffice? Updated the old version or a clean install?

**Comment by uncertainquark** [comment]
I'm using Fedora 31. I installed OnlyOffice via the .rpm file available on your website. Tried both upgrading to a new version with an existing install and a clean install.

**Comment by XDmitryK** [comment]
I'm cheked your case in clear Fedora 31 and Onlyoffice 5.4.2-30. I see new non-default fonts
How you install font?
Check the folder (/usr/share/fonts/) for availability non-default fonts
![Fedora 31  Running  - Oracle VM VirtualBox 2019-12](https://user-images.githubusercontent.com/46962983/70222147-9c009200-175a-11ea-91c2-672018a2121a.png)

**Comment by uncertainquark** [comment]
I installed fonts using the built-in GNOME Fonts app. I have the fonts file in ".ttf" format. I double click on it and it opens in GNOME Fonts app where I can install it. OnlyOffice until 5.4.1 then could read those fonts.

**Comment by XDmitryK** [comment]
@uncertainquark I also installed fonts using GNOME applications, and they work fine in OO.
You can to try this on clear OS?

**Comment by uncertainquark** [comment]
Don't have Clear OS installed.

**Comment by XDmitryK** [comment]
Sorry but also i tryed install new font's on ubuntu 18.04\19.04 and they work correctly
I don't have more idea for resolution your issue.I think this only repeats on your system specifically

**Comment by uncertainquark** [comment]
Hi, thanks for looking into this and sorry that information that I'm providing isn't useful. I installed the fonts Droid Serif and Merriweather. Both are available on Google fonts.

**Comment by XDmitryK** [comment]
Do not worry, we are glad that the problem was solved

**Comment by uncertainquark** [comment]
No, the problem wasn't solved. I was responding to the following:
> What a font you added?
 I installed the fonts Droid Serif and Merriweather. Both are available on Google fonts to install.

v5.4.2 doesn't show these but v5.4.1 does.

**Comment by XDmitryK** [comment]
Ok, then I will look for a solution to this problem

**Comment by XDmitryK** [comment]
I also checked the case when we update version 5.4.1 to 5.4.2 and there is no problem with adding fonts
@ShockwaveNN I think you can close this issue because the problem is single

**Comment by uncertainquark** [comment]
Hey, I did a fresh install of Ubuntu 18.04 LTS. And then installed v.5.4.1 of OnlyOffice on it. It worked fine. And read fonts (Droid Serif and PT Sans) that I installed manually from Google fonts.

But then I upgraded to v5.4.2 and it's again not reading system fonts. Both Droid Serif and PT Sans are missing from the font list. And wherever I've used that font, it is not showing the same.

I'm pretty sure now it's a bug. Previously I was on Fedora, now I'm on Ubuntu. Happens on both.

**Comment by uncertainquark** [comment]
Does it maybe have to do with the new binary file. I notice a big difference in the sizes of the OnlyOffice binaries of the two versions:
v5.4.1 is ~380 MB
v5.4.2 is ~160 MB

Is there some major component missing in the new version?

**Comment by terefang** [comment]
OS: Linux Mint 19.2 Tina x86_64
OO-Version: 5.4.2.30

i have some 40 user installed fonts in $HOME/.fonts/... and $HOME/.local/share/fonts/...

all these fonts are recognized in LibreOffice and FontManager but not in OnlyOffice

**Comment by XDmitryK** [comment]
@terefang Yes, it's bug
But if you move .ttf file in /usr/share/fonts or installed fonts using Software Manager in Linux Mint then fonts work correctly, i checked this

**Comment by uncertainquark** [comment]
Hi, but users shouldn't have to do that. The program should just work like it did until v5.4.1

**Comment by XDmitryK** [comment]
@uncertainquark About your problem, it repeats only with you
As for the problem above from @terefang , it is already fixed and the fix will be available in the next update

**Comment by uncertainquark** [comment]
As noted above, I tried on multiple operating systems with both fresh installs and upgrades, and the problem persists. :/

**Comment by terefang** [comment]
@XDmitryK moving fonts to /usr/share/fonts is not possible for non-root users.
according to XDG ([https://wiki.archlinux.org/index.php/XDG_Base_Directory])
/usr/share/fonts and $HOME/.local/share/fonts must be read with $HOME/.fonts 
being the fontconfig compatiblity directory.

thanks for fixing, but since you mentioned only .ttf, will .otf also work ?

any timeframe for the next update ?

**Comment by XDmitryK** [comment]
@terefang yes, .otf we also support
As for the release, I can’t say when the next update will be so there is no information
@uncertainquark We need your OS in VDI formats so that we can repeat this. You can upload OS on any file hosting?

**Comment by uncertainquark** [comment]
> We need your OS in VDI formats so that we can repeat this. You can upload OS on any file hosting?

How do I do this?

**Comment by uncertainquark** [comment]
To be clear, v5.4.2 doesn't load user installed fonts. It loads system fonts.

**Comment by XDmitryK** [comment]
@terefang We fixed this
https://github.com/ONLYOFFICE/desktop-sdk/commit/ac1f4b64b921b9feacc436fee23e71b5ecb13cd1

**Comment by ShockwaveNN** [comment]
DesktopEditors 5.5.1 released. This issue should be fixed.
