### ISSUE TITLE
Cannot reduce window size

### ISSUE THREAD

**Issue by raphmim** [ONLYOFFICE/DesktopEditors#379]
**Do you want to request a *feature* or report a *bug*?**
I'm not sure whether this is a bug or an enhancement request, as I'm not sure whether this behavior is normal

**What is the current behavior?**
I almost cannot reduce the size of the window. I takes almost the entirety of my 13inch screen.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Open any OnlyOffice window
2. Try to resize the window

**What is the expected behavior?**
Be able to reshape the window to whatever shape we want (including very small, such as half the screen or a quarter of the screen) to be able to work on several windows side by side

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Mac OS 10.15.4, OnlyOffice 5.5.1

**Comment by Rita-Bubnova** [comment]
Hello, @Raph33.
At the moment, you cannot reduce the size of the window since this size is set as the minimum for ONLYOFFICE Desktop Editors.
But we will discuss with our development team the possibility of  resizing the window Desktop Editor (issue 45135 in our internal issue tracker).

**Comment by Raph33** [comment]
Thank you @Rita-Bubnova 

While I'm a big fan of OnlyOffice, this and #363 are showstoppers when it comes to making it my primary document processor.

**Comment by Brummell67** [comment]
I've same problem, and I add: the window doesn't memorize last shape (dimensions) setted, and each time reopening, show default settings (for me, too big).
Thank

**Comment by Rita-Bubnova** [comment]
Hello, @Brummell67.
I'm not sure I can reproduce the problem " the window doesn't memorize last shape (dimensions) setted, and each time reopening, show default settings (for me, too big)".
What is the diagonal of your monitor? Can you send screenshots or video demonstrating the problem?

**Comment by Brummell67** [comment]
Hello @Rita-Bubnova ,
I open "OnlyOffice and the window is so:
![Annotazione 2020-05-12 163846](https://user-images.githubusercontent.com/5261273/81705630-8745ca00-946f-11ea-95e6-08a17c389534.png)
I reduce the dimensions:
![Annotazione 2020-05-12 163846 B](https://user-images.githubusercontent.com/5261273/81705782-b2c8b480-946f-11ea-889c-eb7898898529.png)
I reboot and  application show like first time (large).
That doesn't happen always, but often.
Thank for your reply.

**Comment by maxkadushkin** [comment]
Hello, @Brummell67,
we can't reproduce it on our systems, so to understand causes we need detailed sequence of your actions before bug happen

> I reboot and application show like first time
do you reboot your PC or app?
does app close correctly before bug?
how many monitors in your system and what is resoultion of them?

**Comment by Brummell67** [comment]
Just happened.
That happen after reboot App. Closing is good.
Monitor HP 2011x, resolution used: 1600x900.
GPU GTX650.

**Comment by maxkadushkin** [comment]
Simply open application -> resize main window -> close main window -> open application again, yes?

**Comment by maxkadushkin** [comment]
it seems I have some actions to repeat the bug

**Comment by Brummell67** [comment]
> Simply open application -> resize main window -> close main window -> open application again, yes?
Correct.
Thank.

**Comment by LackoDan** [comment]
I have the same issues:
- Not being able to have to editors open side by side on my 13" monitor is preventing me from using OnlyOffice as my  main editor. Any updates on this @Rita-Bubnova? 
- @maxkadushkin: I can confirm this his also resets the window dimensions for me: Open application -> resize main window -> close main window -> open application again

**Comment by medneumi** [comment]
Has there been any updates for the issue 45135 identified above?
Thanks

**Comment by ShockwaveNN** [comment]
@medneumi Thanks for noticing, OP issue should be resolved via https://github.com/ONLYOFFICE/desktop-apps/commit/fbb8d0b990e2b313d496689344d758a366fd6ced and should be released in v5.4 long time ago

But OP issue was filed only for the macOS system

I'll close this issue, feel free to comment if you still got this issue on Mac

But if you got a similar issue on another system - it's better to create a new issue

**Comment by medneumi** [comment]
@ShockwaveNN 
Unfortunately, I am still experiencing this issue with v7.0.1 on macOS 11.6.5. The most I can resize the window is down to ~ 1025w x 580h. The height is acceptable in my opinion but as stated by others above, the width minimum limit becomes problematic on smaller screens.

**Comment by ShockwaveNN** [comment]
@medneumi Ok thanks, I'll reopen in and we take a look at this issue again

**Comment by Gingetsu** [comment]
Hello, @medneumi.
We know about this behaviour. We discuss this issue with our development team (issue 40055 in our internal issue tracker).

**Comment by Candyhands** [comment]
Please please fix this. It is the one thing that makes onlyoffice entirety unusable in my workflow. It makes running any other app on the same monitor too much of a labor to consider running

**Comment by LuizSerapiao** [comment]
Just leaving another comment so this issue thread and issue wont be forggotten

**Comment by dronkit** [comment]
Same here. I'm on onlyoffice 7.1.1.57 on pop OS 20.04 and the thing is the onlyoffice window has a minimum size. I'm OK with a minimum height, but the minimum width is a pain when trying to compare documents side by side. I can´t put two documents together on the screen side by side, they don´t fit and they won´t let me resize them any narrower.

**Comment by iqbaltaufiq** [comment]
https://user-images.githubusercontent.com/34777908/201651082-001543e2-0395-419c-ad57-a055bb76369c.mp4

I have the same problem. Cannot resize the window, and it looks like Onlyoffice runs on the top of the window stack since my youtube Picture-in-Picture and Plank dock can't show up while opening onlyoffice.

I'm using Onlyoffice 7.0.2.5 installing from a .deb package on a Linux Mint 19.3 Mate.
My screen size is 14 inch, resolution 1366x768.

**Comment by ekasprzak** [comment]
I'm using 7.2.1.36 (flatpak) and seems like it has been fixed there, thanks a lot!

**Comment by Rita-Bubnova** [comment]
Sorry, we forgot to mention that issue was fixed.
I close this issue. Feel free to comment or reopen it if you got further questions.
