### ISSUE TITLE
Linux Document Bullets

### ISSUE THREAD

**Issue by ronindev** [ONLYOFFICE/DesktopEditors#42]
Bug

I've attached a document with 3 list items, decorated with bullets. In OnlyOffice that bullets look like a non-printed character.
[Document1.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/1010680/Document1.docx)

I've also attached screenshots from LibreOffice, MS Office, OnlyOffice.
My current version is 4.2.5.312. Ubuntu 16.10 
LibreOffice:
![selection_188](https://cloud.githubusercontent.com/assets/921324/26200115/71337ae6-3bd5-11e7-960e-dd0227826fbe.png)

MS Office (Windows):
![image_2017-05-18_14-06-12](https://cloud.githubusercontent.com/assets/921324/26200105/6285085c-3bd5-11e7-847e-8bcd0b3425fc.png)

OnlyOffice
![selection_187](https://cloud.githubusercontent.com/assets/921324/26200122/7ab6ae80-3bd5-11e7-8a05-be7bae8cf000.png)

**Comment by maxkadushkin** [comment]
is there 'Symbol' font in the system? it seems app matched not appropriate font instead of 'Symbol'

**Comment by ronindev** [comment]
I have only 'Symbola' font installed

**Comment by vatterspun** [comment]
Maybe it would be useful to describe how you generated that document.  Did you make it in Word and then try to open it in LibreOffice and OnlyOffice?  Or another program?

**Comment by ronindev** [comment]
Document was created in MS Word

**Comment by JGH1000** [comment]
+1 Same with my LibreOffice and MS Word Documents

**Comment by rezayds** [comment]
Anyone have fixing the problem?

**Comment by ShockwaveNN** [comment]
I think this issue should be resolved by now. Feel free to comment if not

**Comment by serovar** [comment]
The issue is not resolved for me. Using the last official RPM package on Fedora 31.

**Comment by XDmitryK** [comment]
@serovar Which file you used? Can you attach this file?

**Comment by serovar** [comment]
Here it is:

[elenco.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/3874293/elenco.docx)

![Screenshot_2019-11-21_11-58-21](https://user-images.githubusercontent.com/6732420/69332091-dee84300-0c4d-11ea-9cc7-d3139c2f3dd2.png)

**Comment by kbauer** [comment]
I can confirm this issue to still exist on OpenSuse 15.1 64bit. RPM installation didn't work entirely, but only because one package had a deviating name and was already present on the system.
![image](https://user-images.githubusercontent.com/7498468/117009881-7e877d00-acec-11eb-9f21-a334040d13fd.png)
