### ISSUE TITLE
[Bug] No Speech Option

### ISSUE THREAD

**Issue by zero77** [ONLYOFFICE/DesktopEditors#486]
**What is the current behavior?**
When i follow the instructions in the [reed me](https://github.com/ONLYOFFICE/plugin-speech/blob/master/README.md) there is no speech option.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
**What is the expected behavior?**
As described [here](https://github.com/ONLYOFFICE/plugin-speech/blob/master/README.md), there should be an option to read aloud from the plugins tab.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Debian sid
onlyoffice-desktopeditors 5.6.4 (snap edge)

![image](https://user-images.githubusercontent.com/16563034/94340223-f58ec180-fff7-11ea-9ae7-2dc9ad755ef6.png)

![image](https://user-images.githubusercontent.com/16563034/94340176-9630b180-fff7-11ea-9558-8f709d661c78.png)

**Comment by ShockwaveNN** [comment]
Hi, sorry for incorrect info

Speech plugin is not in DesktopEditors
We fixed this is readme here https://github.com/ONLYOFFICE/plugin-speech/pull/11

You can try to add it manually, but need to change API key on your own (and seems we do not have detailed instruction how to do it)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by bmullan** [comment]
Its 2024, four years later and this still does not work??

Will it ever be fixed?

**Comment by VladimirProkofiev52** [comment]
Hello! @bmullan 
This issue is a duplicate. 
Please continue all discussions here: https://github.com/ONLYOFFICE/snap-desktopeditors/issues/115
